### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: 프롬 Prom 소셜 디스커버리
email: promxrcom@gmail.com
description: 나를 높이는 주변 10명 만들기, 프로젝트 프롬
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://promxr.com" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#efeeff'
twitter_username: promxr
github_username:  promxr
author: Jesse Lee
logo: assets/images/og_image.png
twitter:
  username: promxrdsad
social:
  name: Promxr
  links:
    - https://twitter.com/promxr
    - https://www.facebook.com/promxr
    - https://www.linkedin.com/in/promxr
    - https://plus.google.com/+promxr
    - https://github.com/promxr

languages: ["en"]
ampdir: amp

github: https://github.com/unleesh/promxrlanding

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
google_analytics: UA-206899194-1
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

cookie_consent: true
channel_io : true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
