name: PROM 프롬
description: 인정받은 부캐들의 안전한 소셜 디스커버리
full_description: '"나의 일상 주변 사람 10명의 평균이 나다."
<br>
<br>✅ 서울대와 카이스트 멤버들이 모여 만든 최고의 소셜 디스커버리! 
<br>✅ 새로운 사람을 만나고 싶지만 안전한 만남일지 걱정되시죠? 그래서 프롬이 준비했습니다! 실제 지인이 초대해야지만 가입할 수 있는 프롬에서 만남을 시작해보세요!
<br>
<br>  &nbsp;많은 여성들이 온라인으로 사람을 만나는 것이 꺼려지는 이유로 바로 ‘안전하지 않음”을 말하고 있습니다. 이용자가 자신의 안전을 걱정한다면 과연 좋은 만남이 이뤄질 수 있을까요? 여성은 자신의 안전을 걱정하지 않아도 되고, 남성은 자신을 증명하지 않아도 되는 환경에서의 만남이라면 어떨까요! 그래서 저희 팀은 더 안전한 소셜디스커버리, 프롬 PROM을 만들었습니다. 
<br>
<br>  &nbsp;전국의 직장인, 대학생, 그리고 외국에 거주하는 여성 100명을 직접 인터뷰하여 여성의 안전을 위한 초대 기반 서비스를 만들었습니다. 안전한 프롬에서 나의 인생을 더 빛나게 해줄, 나의 평생 친구, 동네친구, 동반자를 만나보세요!  
<br>
<br>  프롬이 당신을 환영합니다!
<br>
<br>
<br> [초대 기반으로 확실한 안전을 보장! 💌]
<br> &nbsp; 초대받지 못한 남성은 들어올 수 없어요! 주변 지인에게 인정받은 남성과 안전하고 셀레는 만남 시작해보세요!
<br>
<br> [자신의 프로필을 보호! 자신이 좋아요한 사람에게만 보여져요!🔑]
<br> &nbsp; 여성이 좋아요한 남성들에게만 프로필이 공개됩니다. 자신의 프로필이 마구잡이로 보여지는 것이 싫은 사람은 다 프롬으로 모여~
<br> 
<br> [올릴 사진이 없을 때는?! 포토메이트 매칭📸]
<br> &nbsp; 사진만 바꿔도 매칭 확률이 올라간다는 사실 알고 계신가요? 프롬은 포토메이트 매칭 서비스를 제공합니다! 주변에 있는 사진 고수와 실시간 매칭 후 프로필 사진 촬영 예약!
<br> 포토메이트와 함께 자신의 매력을 끌어올리세요!
<br>
<br> [매일 밤 9시 50분 오늘의 추천친구!😊]
<br> &nbsp; 하루 한명 추천으로 진지한 만남을 시작하세요!
<br>'

android: https://play.google.com/store/apps/details?id=com.promxr.app
iOS: https://apps.apple.com/us/app/prom-%ED%94%84%EB%A1%AC/id1585055350
web: https://telegra.ph/Replace-this-link-07-23
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
  - 5.png
  - 6.png
  - 7.png
  - 8.png
producthunt: https://telegra.ph/Replace-this-link-07-23
# companies:
#   - url: https://telegra.ph/Replace-this-link-07-23
#     image: androidpolice.png
#   - url: https://telegra.ph/Replace-this-link-07-23
#     image: producthunt.png
