name: PROM 프롬
description: 인정받은 부캐들의 안전한 소셜 디스커버리
full_description: '"나의 일상 주변 사람 10명의 평균이 나다."<br>
<br>
<br>서울대와 카이스트 맴버들이 처음에는 최고의 소셜 추천 알고리즘을 만들고자 모였습니다.
<br>하지만 알고리즘이 문제가 아니라 여성들은 온라인으로 사람 만나는 앱이 안전하지 않다고, 데이팅 앱을 쓰는 것을 자연스럽게 말하지 못하는게 더 해결해야 할 문제였습니다.
<br>
<br>온라인에서의 새로운 만남은 새로운 기회와 성장을 가져다 줍니다.
<br>하지만 여성들이 안전하다고 생각하지 않는다면, 멀쩡한 남성들도 잠재적 가해자로 간주될 수 있다면 어떻게 좋은 만남이 이뤄질 수 있을까요?
<br>
<br>그래서 저희들은 더 안전한 소셜 디스커버리(단순 남녀의 가벼운 만남, 조건을 보고 만나는 만남이 아닌) 앱으로 더 좋은 사람들을 만나고 싶어서, 더 안전한 환경을 만들고 싶어서 프롬을 만들었습니다.
<br>
<br>전국의 직장인, 대학생, 그리고 외국에 거주하는 여성분들까지 한 분 한분 100명을 인터뷰하여 정리한 내용을 바탕으로 기본부터 바로 선 안전한 온라인 만남, 소셜 디스커버리 앱 프롬이 나왔습니다.
<br>
<br>"안전하다면!"
<br>오늘 온라인에서 만난 그 사람이 나의 인생을 더 빛나게 해줄지도, 나의 평생 친구, 동반자가 되어줄지도 모르는 것 아닐까요?
<br>
<br>프롬.
<br>오늘 시작해 보세요
<br>'

android: https://play.google.com/store/apps/details?id=com.promxr.app
iOS: https://apps.apple.com/us/app/prom-%ED%94%84%EB%A1%AC/id1585055350
web: https://telegra.ph/Replace-this-link-07-23
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
producthunt: https://telegra.ph/Replace-this-link-07-23
# companies:
#   - url: https://telegra.ph/Replace-this-link-07-23
#     image: androidpolice.png
#   - url: https://telegra.ph/Replace-this-link-07-23
#     image: producthunt.png
